# Generated by Django 4.0.6 on 2022-07-23 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buckets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buckets.paper'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='ordinal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ordinal'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
