# Generated by Django 4.0.6 on 2022-10-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='background_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buckets.background_color'),
        ),
    ]
