# Generated by Django 4.0.6 on 2022-10-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinal',
            name='ordinal',
            field=models.IntegerField(unique=True),
        ),
    ]
